# Generated by Django 5.1.4 on 2024-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osusena_zemlja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlazna', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preradjena_zemlja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sirova_zemlja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vlazna_Zemlja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlazna', models.BooleanField(default=True)),
            ],
        ),
    ]
