# Generated by Django 5.1.4 on 2024-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osusena_zemlja',
            name='kolicina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlazna_zemlja',
            name='kolicina',
            field=models.IntegerField(default=0),
        ),
    ]
