# Generated by Django 5.1.4 on 2025-01-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_rename_preradjena_zemlja_glina_delete_osusena_zemlja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina_g', models.IntegerField(default=0)),
            ],
        ),
    ]
