# Generated by Django 5.1.4 on 2025-01-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_grumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoblikovanCrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojN', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OblikovanCrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojO', models.IntegerField(default=0)),
            ],
        ),
    ]
