# Generated by Django 5.1.4 on 2025-01-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_neoblikovancrep_oblikovancrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsusenCrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojOS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VagonPecenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojVP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VagonSusenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojVS', models.IntegerField(default=0)),
            ],
        ),
    ]
