# Generated by Django 5.1.4 on 2025-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_osusencrep_vagonpecenje_vagonsusenje'),
    ]

    operations = [
        migrations.CreateModel(
            name='IspecenCrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojIC', models.IntegerField(default=0)),
            ],
        ),
    ]
