# Generated by Django 5.1.4 on 2025-01-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_ispecencrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketCrepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojPC', models.IntegerField(default=0)),
            ],
        ),
    ]
